blank_issues_enabled: false
contact_links:
  - name: ROR Roadmap Discussion Forum
    url: https://github.com/ror-community/ror-roadmap/discussions
    about: Discuss your ideas and suggestions with the ROR community (start here if you don't have enough information to complete the issue template)
  - name: ROR Tech Support
    url: https://groups.google.com/a/ror.org/g/ror-api-users
    about: Get help using ROR tools and services
